import { Grid, Typography } from "@material-ui/core";
import React from "react";
import "./Whychooseus.css";
export const Whychooseus = () => {
  return (
    <div style={{ margintop: "7%" }}>
      <h1 className="choose">Why grow with us?</h1>
      <Grid container>
        <Grid item md={1} />
        <Grid item md={5} style={{ marginTop: "2%" }}>
          <img src="https://3841ex3t1et33uno5h3thxr7-wpengine.netdna-ssl.com/wp-content/uploads/2020/07/studio-team.jpg" />
        </Grid>
        <Grid item md={5}>
          <div className="rectangle">
            <Typography className="line1">
              Revenue Generated By Our Clients in 2020
            </Typography>
            <Typography className="line2">$26,369,321</Typography>
          </div>
          <div className="rectangle2">
            <Typography className="line1">
              Client Average Revenue Growth YoY
            </Typography>
            <Typography className="line2">90%</Typography>
          </div>
          <div className="rectangle3">
            <Typography className="line1">
              Our Design Clients Sell on Average
            </Typography>
            <Typography className="line2">4X More</Typography>
          </div>
          <div className="rectangle4">
            <Typography className="line1">Managed Ad Spend</Typography>
            <Typography className="line2">$4,000,000+</Typography>
          </div>
        </Grid>
        <Grid item md={1} />
      </Grid>
      <img
        className="partner"
        src="https://3841ex3t1et33uno5h3thxr7-wpengine.netdna-ssl.com/wp-content/uploads/2020/07/partner-logos.jpg"
      />
    </div>
  );
};
